# -*- coding: utf-8 -*-
"""calc_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W0BgtotxllsQTXZci7d9vB4jHwm_woXg
"""

def menu():
  print("ESCOHA A OPERAÇÃO: \n")


def soma(num1,num2):
    resultado = num1+num2
    return resultado 

def subtracao(num1,num2):
    resultado = num1-num2
    return resultado 

def multiplicacao(num1,num2):
    resultado = num1*num2
    return resultado 

def divisao(num1,num2):
    resultado = num1/num2
    return resultado 

def operacao(opcao,n1,n2):
  if opcao == "soma":
    return soma(n1,n2)
  elif opcao == "subtração":
    return subtracao(n1,n2)
  elif opcao == "multiplicação":
    return multiplicacao(n1,n2)
  elif opcao == "divisão":
    return divisao(n1,n2)
  else:
    return "erro, coloque uma operação válida"

print("digite dois numeros e depois escolha a operação: \n")
num1 = int(input())
num2 = int(input())
menu()
op = input()
print(operacao(op,num1,num2))